// Array
var Fruits = new Array("Apple" , "Cherry" , "Orange");
var Fruits = ["Apple", "Cherry", "Orange"];
Fruits[0] = "Watermelon";
let Arrays = "Amir-Meyti-Hosein-Mamad-Ashkan";
Arrays = Arrays.split("-");
document.write(Fruits);
document.write("<br>");
console.log(Fruits.indexOf("Orange"));
document.write(Fruits[1]);
document.write("<br>");
Fruits.push("Banana");
Fruits.push("25");
Fruits.sort();
document.write(Fruits);
document.write("<br>");
console.log(typeof Fruits);
document.write(Arrays);
document.write("<br>");
document.write(typeof Arrays);